thenxparser/thenx/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static
from .forms import AuthenticationForm

app_name = 'thenx'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dash_view, name='dashboard'),
    path('dashboard/products/', views.products_view, name='products'),
    path('dashboard/products/<str:sku>', views.redirecttoproduct, name='specificproduct'),
    path('dashboard/products/delete/(<urlid>)/(<pid>)', views.deleteurl, name='deleteurl'),
    path('dashboard/products/setimp', views.set_imp, name='setimp'),
    path('dashboard/rules/parser', views.rules_parser, name='parserrules'),
    path('dashboard/rules/pricelist', views.rules_price_list, name='pricelistrules'),
    path('dashboard/rules/margins', views.rules_margins, name='marginsrules'),
    path('dashboard/rules/vat', views.rules_vat, name='vatrules'),
    path('dashboard/rules/warranty', views.rules_warranty, name='warrantyrules'),
    path('dashboard/rules/', views.rules_view, name='rules'),
    path('rules/getDetails/', views.getDetails, name='details'),
    path('validatesku/', views.validateSKU, name='validatesku'),
    path('dashboard/rules/delete/(<ruleid>)/(<rule>)', views.deleterule, name='deleterule'),
    path('dashboard/products/uploadcompetitors/', views.competitors_upload, name='uploadcomp'),
    path('dashboard/downloadpricelist/', views.downloadpricelist, name='downloadpricelist')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thenxparser/thenxparser/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'ThenXParser Administration'

urlpatterns = [
    path('', include('thenx.urls')),
    path('admin/', admin.site.urls),
]

thenxparser/thenx/forms.py
from django.contrib.auth.forms import AuthenticationForm as BaseAuthenticationForm
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext, gettext_lazy as _
from django import forms
from .models import UploadCompetitors


class AuthenticationForm(BaseAuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'form-control',
        'placeholder': _('User')
    }))
    password = forms.CharField(strip=False,
                               widget=forms.PasswordInput(attrs={
                                   'autocomplete': 'current-password',
                                   'class': 'form-control',
                                   'placeholder': _("Password")
                               }))
#
# class upload_comps(forms.ModelForm):
#     # compfile = forms.FileField(
#     #     label="Select a file containing competitor URLS",
#     #     help_text='max. 500 megabytes'
#     # )
#
#     def __init__(self, *args, **kwargs):
#         super(upload_comps, self).__init__(*args, **kwargs)
#         self.fields['upload_file'].widget.attrs['class'] = 'fileUpload btn btn-outline-primary btn-lg btn-block'
#
#     class Meta:
#         model = UploadCompetitors
#         fields = [
#             'upload_file',
#         ]

thenxparser/thenx/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from .forms import *
from django.core.paginator import Paginator
from .models import *
from .tasks import *
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from datetime import timedelta
import json
import io
from django.core.files.storage import FileSystemStorage

# For login required @login_required(login_url='thenx:login')
def index(request):
    if request.user.is_authenticated:
        return redirect('thenx:dashboard')
    return redirect("thenx:login")


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('thenx:dashboard')
    else:
        form = AuthenticationForm()
        if request.user.is_authenticated:
            return redirect('thenx:dashboard')

    return render(request, 'thenx/login.html', {'form': form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('/')


@login_required(login_url='thenx:login')
def dash_view(request):
    totalp = Product.objects.count()
    totalc = Competitor_URL.objects.count()
    comp = Competitor_URL.objects.order_by('comp_name').values_list("comp_name", flat=True).distinct()

    brands = Product.objects.order_by("brand").values_list("brand", flat=True).distinct()
    tbrands = len(brands)
    suppliers = Product.objects.order_by("supplier").values_list("supplier", flat=True).distinct()
    categories = Product.objects.order_by("category").values_list("category", flat=True).distinct()
    categories = ", ".join(categories)
    categories = categories.split(', ')
    categories = list(set(categories))
    tcats = len(categories)
    delta = datetime.now() - timedelta(days=1)
    recentlychanged = Product.objects.filter(dateupdated__gte=delta)
    increased = 0
    decreased = 0
    for o in recentlychanged:
        if o.price_list_set.first().finalprice > o.oldprice:
            increased += 1
        else:
            decreased += 1

    recentlychanged = recentlychanged.count()
    imcheapest = 0
    imcheaper = 0
    imaverage = 0
    imhigher = 0
    imhighest = 0
    imequal = 0
    for p in Product.objects.all():
        comp_prices = list(p.competitor_url_set.order_by('comp_price').values_list('comp_price', flat=True))
        if len(comp_prices) == 0:
            imequal += 1
            continue
        price = round(p.price_list_set.first().finalprice, 1)
        comp_prices.append(price)
        comp_prices.sort()
        idx = comp_prices.index(price)
        if len(set(comp_prices)) <= 1:
            imequal += 1
            continue

        if idx == 0:
            imcheapest += 1
        elif 0 < idx < len(comp_prices)//2:
            imcheaper += 1
        elif idx == len(comp_prices)//2:
            imaverage += 1
        elif len(comp_prices)//2 < idx < len(comp_prices) - 1:
            imhigher += 1
        else:
            imhighest += 1

    pindex = 96.91
    complist = [[] for _ in range(len(comp))]

    for idx, c in enumerate(complist):
        comp_name = list(comp)[idx]
        complist[idx].append(comp_name)
        complist[idx].append(Competitor_URL.objects.filter(comp_name__contains=comp_name).count())
        complist[idx].append(40)
        complist[idx].append(0)

    complist.insert(0, ["thenx", Product.objects.count(), 96.5, 0])

    comp = comp.count()
    if request.method == 'GET':
        brandq = False
        supq = False
        catq = False
        if 'q' in request.GET:
            query = request.GET.get('q')
            plist = Product.objects.filter(
                Q(SKU__icontains=query) | Q(name__icontains=query) | Q(brand__icontains=query))
        else:
            plist = Product.objects.all()

        if 'brand' in request.GET:
            brandq = True
            query = request.GET.get('brand')
            if query != 'All' and query != None:
                plist = Product.objects.filter(Q(brand__icontains=query))
            else:
                plist = Product.objects.all()

        if 'supplier' in request.GET:
            supq = True
            query = request.GET.get('supplier')
            if query != 'All' and query != None:
                plist = Product.objects.filter(Q(supplier__icontains=query))
            else:
                plist = Product.objects.all()

        if 'category' in request.GET:
            catq = True
            query = request.GET.get('category')
            print(query)
            if query != 'All' and query != None:
                plist = Product.objects.filter(category__icontains=query)
            else:
                plist = Product.objects.all()

    paginator = Paginator(plist, 100)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    # UpdateDB()
    return render(request, 'thenx/dashboard.html', {
        'totalp': totalp,
        'totalc': totalc,
        'comp': comp,
        'list': products,
        'brands': brands,
        'recentlychanged': recentlychanged,
        'suppliers': suppliers,
        'categories': categories,
        'tcats': tcats,
        'tbrands': tbrands,
        'increased': increased,
        'decreased': decreased,
        'imcheapest': imcheapest,
        'imcheaper': imcheaper,
        'imaverage': imaverage,
        'imhigher': imhigher,
        'imhighest': imhighest,
        'imequal': imequal,
        'pindex': pindex,
        'complist': complist,
        })


def get_count_users():
    return User.objects.count()

def competitors_upload(request):
    if request.method == "POST":
        compurls = request.FILES["compurls"]
        p = UploadCompetitors.objects.create(upload_file=compurls)
        # print(p)
        upload_comps()
        print(compurls)

        return JsonResponse({"result": "True"})
    else:
        return JsonResponse({"result": "False"})
@login_required(login_url='thenx:login')
def products_view(request):
    # UpdateDB()
    brands = Product.objects.order_by("brand").values_list("brand", flat=True).distinct()
    plist = Product.objects.all()
    suppliers = Product.objects.order_by("supplier").values_list("supplier", flat=True).distinct()
    categories = Product.objects.order_by("category").values_list("category", flat=True).distinct()
    # categories = list(set(x for l in categories for x in l))
    categories = ", ".join(categories)
    categories = categories.split(', ')
    categories = list(set(categories))

    if request.method == "POST":
        urldata = request.POST.dict()
        url = urldata.get("url")
        p = urldata.get("product")
        p = Product.objects.filter(SKU=p).first()
        if p.competitor_url_set.filter(url=url).count() == 0:
            c = p.competitor_url_set.create(url=url)
            c.scrap()
            p.update_competitorprices()
        else:
            messages.error(request, "This URL Already Exists")
        queryflag1 = False
        queryflag2 = False
        if 'q' in request.GET:
            query = request.GET.get('q')
            queryflag1 = True
            return HttpResponseRedirect('.' + '?q=' + str(query))

        if 'brand' in request.GET:
            bquery = request.GET.get('brand')
            queryflag2 = True
            return HttpResponseRedirect('.' + '?brand=' + str(bquery))

        # if queryflag1 or queryflag2:
        #     return HttpResponseRedirect('.' + '?brand=' + str(bquery) + '&' + 'q=' + str(query))
        # elif queryflag1:
        #     return HttpResponseRedirect('.' + '?q=' + str(query))
        # elif queryflag2:
        #     return HttpResponseRedirect('./' + '?brand=' + str(bquery))
        # else:
        return redirect('thenx:products')

    if request.method == "GET":
        if 'q' in request.GET:
            query = request.GET.get('q')
            print(query)
            plist = Product.objects.filter(
                Q(SKU__icontains=query) | Q(name__icontains=query) | Q(brand__icontains=query))
        else:
            plist = Product.objects.all()

        if 'brand' in request.GET:
            brandq = True
            query = request.GET.get('brand')
            if query != 'All' and query != None:
                plist = Product.objects.filter(Q(brand__icontains=query))
            else:
                plist = Product.objects.all()

        if 'supplier' in request.GET:
            supq = True
            query = request.GET.get('supplier')
            if query != 'All' and query != None:
                plist = Product.objects.filter(Q(supplier__icontains=query))
            else:
                plist = Product.objects.all()

        if 'category' in request.GET:
            catq = True
            query = request.GET.get('category')
            if query != 'All' and query != None:
                plist = Product.objects.filter(category__icontains=query)
            else:
                plist = Product.objects.all()

    paginator = Paginator(plist, 50)
    page = request.GET.get('page')
    products = paginator.get_page(page)

    return render(request, 'thenx/products.html', {
        'list': products,
        'brands': brands,
        'suppliers': suppliers,
        'categories': categories,
        'uploadform': upload_comps,
    })


@login_required(login_url='thenx:login')
def deleteurl(request, urlid=None, pid=None):
    o = Competitor_URL.objects.filter(pk=urlid).first()
    p = o.product
    o.delete()
    p.update_competitorprices()

thenxparser/thenx/templates/thenx/dash_base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ThenX -{% block title %} Home {% endblock title %}</title>
    {# Favicon #}
    <link rel="shortcut icon" type="image/png" href="{% static 'thenx/favicon.png' %}"/>
    <!-- Fontfaces CSS-->
    <link href="{% static 'thenx/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
          media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'thenx/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">


    <!-- Vendor CSS-->
    <link href="{% static 'thenx/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet"
          media="all">
    <link href="{% static 'thenx/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'thenx/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'thenx/css/theme.css' %}" rel="stylesheet" media="all">
    <!-- Jquery JS-->
    <script src="{% static 'thenx/vendor/jquery-3.2.1.min.js' %}"></script>
</head>
<body class="animsition">
<!--<p>Welcome to dash</p>-->
<div class="page-wrapper">
    <!-- HEADER DESKTOP-->
    <header class="header-desktop3 d-none d-lg-block">
        <div class="section__content section__content--p35">
            <div class="header3-wrap">
                <div class="header__logo">
                    <a href="{% url 'thenx:dashboard' %}">
                        <img src="{% static 'thenx/dashlogo.png' %}" alt="THENX PARSER"/>
                    </a>
                </div>
                <div class="header__navbar">
                    <ul class="list-unstyled">
                        <li>
                            <a href="{% url 'thenx:dashboard' %}">
                                <i class="fas fa-tachometer-alt"></i>Dashboard
                                <span class="bot-line"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fas fa-shopping-basket"></i>
                                <span class="bot-line"></span>Shop</a>
                        </li>
                        <li>
                            <a href="{% url 'thenx:products' %}">
                                <i class="fas fa-trophy"></i>
                                <span class="bot-line"></span>Products</a>
                        </li>
                        <li>
                            <a href="{% url 'thenx:rules' %}">
                                <i class="fas fa-copy"></i>
                                <span class="bot-line"></span>Rules</a>
                        </li>
                    </ul>
                </div>
                <div class="header__tool">
                    <div class="account-wrap">
                        <div class="account-item account-item--style2 clearfix js-item-menu">
                            <div class="content">
                                <a class="js-acc-btn" href="#">{{user.username}}</a>
                            </div>
                            <div class="account-dropdown js-dropdown">
                                <div class="info clearfix">
                                    <div class="content">
                                        <h5 class="name">
                                            <a href="{% url 'thenx:dashboard' %}">{{user.username}}</a>
                                        </h5>
                                        <span class="email">
                                        {% if user.email %}
                                            {{user.email}}
                                        {% else %}
                                            No Email Provided
                                        {% endif %}
                                        </span>
                                    </div>
                                </div>

                                <div class="account-dropdown__footer">
                                    <form id='dash-logout' action="{% url 'thenx:logout' %}" method="POST">
                                        {% csrf_token %}
<!--                                        <input type="hidden" name="logout" value="{{ request.GET.next }}" />-->
<!--                                        <input class="btn btn-primary btn-md my-2 p" type="submit" value="">-->
                                        <a href="javascript:void(0);" onclick="document.getElementById('dash-logout').submit();">
                                        <i class="zmdi zmdi-power"></i>Logout</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- PAGE CONTENT-->
    <div class="page-content--bgf7">
        <!-- BREADCRUMB-->
        <section class="au-breadcrumb2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="au-breadcrumb-content">
                            <div class="au-breadcrumb-left">
                                <span class="au-breadcrumb-span">You are here:</span>
                                <ul class="list-unstyled list-inline au-breadcrumb__list">
                                    <li class="list-inline-item active">
                                        <a href="{% url 'thenx:dashboard' %}">Dashboard</a>
                                    </li>
                                    <li class="list-inline-item seprate">
                                        <span>/</span>
                                    </li>
                                    <li class="list-inline-item">{% block nav %}Home{% endblock %}</li>
                                </ul>
                            </div>
{#                        Search can be implemented if needed #}
{#                            <form class="au-form-icon--sm" action="" method="post">#}
{#                                <input class="au-input--w300 au-input--style2" type="text" placeholder="Search for products...">#}
{#                                <button class="au-btn--submit2" type="submit">#}
{#                                    <i class="zmdi zmdi-search"></i>#}
{#                                </button>#}
{#                            </form>#}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END BREADCRUMB-->

{% block dashcontent %} {% endblock %}
<!-- COPYRIGHT-->
            <section class="p-t-60 p-b-20">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="copyright">
                                <p>Copyright © 2020 THENX. All rights reserved.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END COPYRIGHT-->
</div>


    <!-- Vendor JS       -->
    <script src="{% static 'thenx/vendor/slick/slick.min.js' %}" >
    </script>
    <script src="{% static 'thenx/vendor/wow/wow.min.js' %}" ></script>
    <script src="{% static 'thenx/vendor/animsition/animsition.min.js' %}" ></script>
    <script src="{% static 'thenx/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %} ">
    </script>
    <script src="{% static 'thenx/vendor/counter-up/jquery.waypoints.min.js' %}" ></script>
    <script src="{% static 'thenx/vendor/counter-up/jquery.counterup.min.js' %}" >
    </script>
    <script src="{% static 'thenx/vendor/circle-progress/circle-progress.min.js' %}" ></script>
    <script src="{% static 'thenx/vendor/perfect-scrollbar/perfect-scrollbar.js' %}" ></script>
    <script src="{% static 'thenx/vendor/chartjs/Chart.bundle.min.js' %}" ></script>
    <script src="{% static 'thenx/vendor/select2/select2.min.js' %}" >
    </script>
    <!-- Bootstrap JS-->
    <script src="{% static 'thenx/vendor/bootstrap-4.1/popper.min.js' %}" ></script>
    <script src="{% static 'thenx/vendor/bootstrap-4.1/bootstrap.min.js' %}" ></script>
    <!-- Main JS-->
    <script src="{% static 'thenx/js/main.js' %} "></script>
    <script>
    $(function () {
        // inspect html to check id of category select dropdown.
        $(document).on('input', "#sku", function () {
            var elem = $("#sku").val();
            $.ajax({
                url: {% url 'thenx:validatesku' %},
                type: 'get',
                data: {sku:elem},
                dataType: 'json',
                success: function(resp){
                    if (resp.result === "False"){
                        $("#skuerror").show();
                    }
                    else{
                        $("#skuerror").hide();
                    };
                }
        });
        });
    })
    </script>
    <script>
    $(function () {
        // inspect html to check id of category select dropdown.
        $(document).on('input', "#sku1", function () {
            var elem = $("#sku1").val();
            $.ajax({
                url: {% url 'thenx:validatesku' %},
                type: 'get',
                data: {sku:elem},
                dataType: 'json',
                success: function(resp){
                    if (resp.result === "False"){
                        $("#skuerror1").show();
                    }
                    else{
                        $("#skuerror1").hide();
                    };
                }
        });
        });
    })
    </script>
        <script>
        $(function () {
            // inspect html to check id of category select dropdown.
            $(document).on('change', "select#selection", function () {
                if ($(this).val() == "sup" || $(this).val() == "cat") {
                    if ($(this).val() == 'sup') {
                        var options = '<option value="">Select Supplier</option>';
                        options += '<option value="all">All Suppliers</option>';
                    } else if ($(this).val() == 'cat') {
                        var options = '<option value="">Select Category</option>';
                        options += '<option value="all">All Category</option>';
                    }
                    $("#skuinput").hide();
                    $("#supcatdiv").show();
                    $.getJSON("{% url 'thenx:details' %}", {'choice': $(this).val()}, function (j) {
                        for (var i = 0; i < j.length; i++) {
                            options += '<option value="' + j[i] + '">' + j[i] + '</option>';
                        }
                        // inspect html to check id of subcategory select dropdown.
                        $("select#supcat").html(options);
                    });
                } else if ($(this).val() == "sku"){
                    $("#supcatdiv").hide();
                    $("#skuinput").show();
                }
                else{
                    $("#supcatdiv").hide();
                    $("#skuinput").hide();
                }
            });
        });

        $(function (){
            $(document).on('change', "select#selection2", function () {
                if ($(this).val() == "sup" || $(this).val() == "cat") {
                    if ($(this).val() == 'sup') {
                        var options = '<option value="">Select Supplier</option>';
                    } else if ($(this).val() == 'cat') {
                        var options = '<option value="">Select Category</option>';
                    }
                    $("#skuinput2").hide();
                    $("#supcatdiv2").show();
                    $.getJSON("{% url 'thenx:details' %}", {'choice': $(this).val()}, function (j) {
                        for (var i = 0; i < j.length; i++) {
                            options += '<option value="' + j[i] + '">' + j[i] + '</option>';
                        }
                        // inspect html to check id of subcategory select dropdown.
                        $("select#supcat2").html(options);
                    });
                } else if ($(this).val() == "sku"){
                    $("#supcatdiv2").hide();
                    $("#skuinput2").show();
                }
                else {
                    $("#supcatdiv2").hide();
                    $("#skuinput2").hide()
                }
            });
        })
    </script>
</div>
</body>

</html>

thenxparser/thenx/templates/thenx/rules.html
{% extends 'thenx/dash_base.html' %}

{% block title %} Rules
{% endblock title %}

{% block nav %}Rules {% endblock nav %}

{% block dashcontent %}
{#    <button type="button" href="" class="btn btn-primary btn-lg btn-block">Primary</button>#}
    <button type="button" class="btn btn-primary btn-lg btn-block"><a href="{% url 'thenx:parserrules' %}" style="color: white">Competitors Parser Rules</a></button>
    <button type="button" class="btn btn-success btn-lg btn-block"><a href="{% url 'thenx:pricelistrules' %}" style="color: white">ThenX Price List Rules</a></button>
    <button type="button" class="btn btn-warning btn-lg btn-block"><a href="{% url 'thenx:marginsrules' %}" style="color: white">Margin Rules</a></button>
    <button type="button" class="btn btn-danger btn-lg btn-block"><a href="{% url 'thenx:vatrules' %}" style="color: white">Set VAT</a></button>
    <button type="button" class="btn btn-dark btn-lg btn-block"><a href="{% url 'thenx:warrantyrules' %}" style="color: white">Warranty</a></button>
{% endblock dashcontent %}

thenxparser/thenx/templates/thenx/rules_vat.html
{% extends 'thenx/dash_base.html' %}

{% block title %}VAT Rules
{% endblock title %}

{% block nav %}VAT Rules {% endblock nav %}

{% block dashcontent %}
    <form action={% url 'thenx:vatrules' %} method="post">
        {% csrf_token %}
        <div class="row form-group col-md-16">
            <label for="selectSm" class="form-control-label" style="padding-left: 1.4%">Rule 1: Add VAT</label>

            <div class="col col-sm-1">
                <input type="text" id="input-small" name="vat" placeholder="VAT in %"
                       class="input-sm form-control-sm form-control">
            </div>
            {% if messages %}
                {% for message in messages %}
                    <span class="badge badge-danger">{{ message }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <button type="button" onclick="this.form.submit()" class="col-md-12 btn btn-outline-success btn-sm"
                style="right: 0%">
            <i class="fa fa-magic"></i>&nbsp; Add rule
        </button>
    </form>
    <hr>
    <br><br>

    {#    Applied Rules List  #}

    <div class="col-md-12">
        {% if rules.count != 0 %}
            <div class="vue-lists">
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="mb-4">Applied Rules:</h2>
                        <ul>
                            {% for r in rules %}
                                <li>
                                    <form action="{% url 'thenx:deleterule' ruleid=r.pk rule="vat" %}"
                                          method="post">
                                        {% csrf_token %}
                                        Add VAT {{ r.vat }}% for all products.

                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                            <i class="zmdi zmdi-delete"></i>
                                        </button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% else %}
            <h3 class="mb-auto">No Rules Applied.</h3>
        {% endif %}
    </div>
{% endblock dashcontent %}